app:
  build: .
  command: npm start
  volumes:
    - ./artifacts:/usr/src/app/artifacts
  ports:
    - "3000:3000"
  environment:
    - CODECLIMATE_REPO_TOKEN
    - RELEASE_ENVIRONMENT
    - STAGING_APP_NAME
    - STAGING_SEARCH_URL
    - STAGING_SENTRY_DSN
    - STAGING_STATSD_HOST
    - STAGING_SLACK_WEBHOOK_URL
    - PRODUCTION_APP_NAME
    - PRODUCTION_SEARCH_URL
    - PRODUCTION_SENTRY_DSN
    - PRODUCTION_STATSD_HOST
    - PRODUCTION_SLACK_WEBHOOK_URL
