steps:
  - name: ":docker:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: native

  - wait

  - name: ":deciduous_tree: Validate .env (staging)"
    command: "bin/buildkite bin/ci run bin/exec-env-validate"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "STAGING"

  - wait

  - name: ":deciduous_tree: Validate .env (production)"
    command: "bin/buildkite bin/ci run bin/exec-env-validate"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "PRODUCTION"

  - wait

  - name: ":mag:"
    command: "bin/buildkite bin/ci run 'npm test'"
    agents:
      - queue=native

  - wait

  - name: ":triangular_flag_on_post:"
    command: "bin/buildkite bin/ci run 'npm run coverage'"
    branches: "master"
    agents:
      - queue=native

  - wait

  - name: ":package: Create release (staging)"
    command: "bin/buildkite bin/ci create-release"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "STAGING"

  - wait

  - name: ":clipboard:"
    command: "bin/ci-terraform-plan staging"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "STAGING"

  - name: ":rocket: Release staging"
    type: "manual"

  - name: ":speech_balloon:"
    command: "bin/buildkite bin/ci announce releasing-staging"
    branches: "master release/*"
    agents:
      - queue=native

  - wait

  - name: ":earth_asia:"
    command: "bin/ci-terraform-apply staging"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "STAGING"

  - wait

  - name: ":package: Create release (production)"
    command: "bin/buildkite bin/ci create-release"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "PRODUCTION"

  - wait

  - name: ":clipboard:"
    command: "bin/ci-terraform-plan production"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "PRODUCTION"

  - wait

  - name: ":speech_balloon:"
    command: "bin/buildkite bin/ci announce ready-to-release-production"
    branches: "master release/*"
    agents:
      - queue=native

  - name: ":rocket: Release production"
    type: "manual"
    branches: "master"

  - name: ":speech_balloon:"
    command: "bin/buildkite bin/ci announce releasing-production"
    branches: "master release/*"
    agents:
      - queue=native

  - wait

  - name: ":earth_asia:"
    command: "bin/ci-terraform-apply production"
    agents:
      - queue=native
    env:
      RELEASE_ENVIRONMENT: "PRODUCTION"

  - wait

  - name: ":speech_balloon:"
    command: "bin/buildkite bin/ci announce released-production"
    branches: "master release/*"
    agents:
      - queue=native
